extraction:
  cpp:
    after_prepare: 
      - python report.py 96
  cobol:
    after_prepare: 
      - python report.py 96
  csharp:
    after_prepare: 
      - python report.py 96
  java:
    after_prepare: 
      - python report.py 96
  javascript:
    after_prepare: 
      - python report.py 96
  python:
    after_prepare: 
      - python report.py 96
